### ISSUE TITLE
与BaseRecyclerViewAdapterHelper一同使用时，划出的按钮点击事件很难响应

### ISSUE THREAD

**Issue by NanayaHaruki** [anzaizai/EasySwipeMenuLayout#10]
是不是被当做滑动来处理了？点击事件是写在adapter.setOnItemChildClickListener（）里的
还有就是setOnItemClickListener（）也不灵了，我把EasySwipeMenuLayout换成LinearLayout就正常了

**Comment by lucklygaj** [comment]
你直接使用View原生的点击事件，使用setOnItemChildClickListener会因为焦点抢占问题，导致失灵

**Comment by lucklygaj** [comment]
直接设置原生的，这样就不会有焦点抢占的问题了
