### ISSUE TITLE
侧滑的控件一直贴着屏幕边上，有什么方法让控件距离屏幕一些距离吗？

### ISSUE THREAD

**Issue by ghost** [anzaizai/EasySwipeMenuLayout#12]
给侧滑布局加入了margin_right也不好使，他显示出来后也一直贴着屏幕

**Comment by lucklygaj** [comment]
你是想让侧滑出来的按钮跟屏幕有个margin？还是内容布局跟屏幕有个margin

**Comment by ghost** [comment]
让侧滑出来的按钮和屏幕有一个margin，item的布局已经和屏幕有一个margin了。

**Comment by lucklygaj** [comment]
这个项目的创建是由一个小伙伴有这么一个需求，然后我就说弄一个吧，没考虑到你这个需求，所以内部是忽略内容view的margin的，你现在可以这样子处理，内容View内部再套一层布局，通过内部布局设置margin应该可以解决，新版本会考虑支持margin这些特性

**Comment by ghost** [comment]
好的，谢谢，我用RecylerView，然后在item中使用你的这个布局，然后设置了一些margin，不知不觉就成功了，listview是不行的，item的布局是一个

**Comment by lucklygaj** [comment]
嗯嗯，感谢你的反馈，listView基本不用了现在
