### ISSUE TITLE
配合下拉刷新使用的时候  侧滑很不灵敏

### ISSUE THREAD

**Issue by lygttpod** [anzaizai/EasySwipeMenuLayout#14]
刷新使用的是android-Ultra-Pull-To-Refresh
禁掉下拉刷新侧滑很灵敏，一起使用的时候要滑动很多次才能出来，这个如何处理

**Comment by lucklygaj** [comment]
你可以试下原生的下拉刷新，看有没有影响，以此判断是否为你的下拉刷新控件产生拉事件拦截或者焦点抢占
