### ISSUE TITLE
侧滑删除之后 重新从服务器刷新数据列表 此时左划状态怎么重置呀

### ISSUE THREAD

**Issue by Comate716** [anzaizai/EasySwipeMenuLayout#15]
而且每一次刷新 处于左划状态的item都会向上移一个位置 很费解

**Comment by lucklygaj** [comment]
可以方便贴一下代码么？你可以调用静态方法getViewCache获得当前状态发生变化的view，然后调用close进行关闭。每次绑定数据时，你需要先重置item的状态，有必要的话。
