### ISSUE TITLE
单独使用EasySwipeMenuLayout这个类，配合RecyclerView使用，内容布局无法铺满父窗口

### ISSUE THREAD

**Issue by tuionf** [anzaizai/EasySwipeMenuLayout#16]
新建一个项目，拷贝  EasySwipeMenuLayout 和 State类到项目中使用，配合RecyclerView，内容布局无法铺满父窗口

代码如下 

MainActivity

`package com.example.tuionf.swipeview;

import android.app.Activity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

public class MainActivity extends Activity {

    private RecyclerView recyclerview;
    private LinearLayoutManager mLinearLayoutManager;
    private String[] datas = new String[50];

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

        recyclerview  = (RecyclerView) findViewById(R.id.recyclerview);

        mLinearLayoutManager = new LinearLayoutManager(this);
        recyclerview.setLayoutManager(mLinearLayoutManager);

        recyclerview.setAdapter(new MyAdapter(this,datas));

    }
}
`

布局文件 
activity_main2

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:clickable="true"
    tools:context="com.example.tuionf.swipeview.MainActivity">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

</LinearLayout>
`

布局item文件  item_layout

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/ll_root"
    android:layout_width="match_parent"

    android:layout_height="wrap_content"
    android:clickable="true"
    android:orientation="vertical">
    /**
    * Created by guanaj on .
    */

    <com.example.tuionf.swipeview.EasySwipeMenuLayout
        android:id="@+id/es"

        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:contentView="@+id/content"
        app:leftMenuView="@+id/left"
        app:rightMenuView="@+id/right">

        <LinearLayout
            android:id="@+id/left"
            android:layout_width="100dp"
            android:layout_height="wrap_content"
            android:background="@android:color/holo_blue_dark"

            android:orientation="horizontal"
            android:padding="20dp">

            <TextView
                android:layout_width="wrap_content"

                android:layout_height="wrap_content"
                android:clickable="true"
                android:text="分享" />

        </LinearLayout>

        <LinearLayout
            android:id="@+id/content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#cccccc"
            android:orientation="vertical"
            android:padding="20dp">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="内容区域" />

        </LinearLayout>

        <LinearLayout
            android:id="@+id/right"

            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@android:color/holo_red_light"
            android:orientation="horizontal">

            <TextView
                android:layout_width="wrap_content"

                android:layout_height="wrap_content"
                android:background="@android:color/holo_blue_bright"
                android:clickable="true"
                android:padding="20dp"
                android:text="删除" />

            <TextView
                android:id="@+id/right_menu_2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@android:color/holo_orange_dark"
                android:clickable="true"
                android:padding="20dp"
                android:text="收藏" />

        </LinearLayout>
    </com.example.tuionf.swipeview.EasySwipeMenuLayout>
</LinearLayout>`

adapter文件 
`package com.example.tuionf.swipeview;

import android.app.Activity;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

/**
 * Created by tuion on 2017/8/4.
 */

public class MyAdapter extends RecyclerView.Adapter<MyAdapter.ViewHolder> {

    private Activity mActivity;
    private String[] datas = null;

    public MyAdapter(Activity mActivity, String[] datas) {
        this.mActivity = mActivity;
        this.datas = datas;
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(mActivity).inflate(R.layout.item_layout,null);
        ViewHolder viewHolder = new ViewHolder(view);
        return viewHolder;
    }

    @Override
    public void onBindViewHolder(ViewHolder holder, int position) {
//        holder.textView.setText(datas[position]+"item——"+position);
    }

    @Override
    public int getItemCount() {
        return datas.length;
    }

    class ViewHolder extends RecyclerView.ViewHolder{
//        public TextView textView;

        public ViewHolder(View itemView) {
            super(itemView);
//            textView = (TextView) itemView.findViewById(R.id.tv);
        }
    }
}
`

**Comment by lucklygaj** [comment]
你的EasySwipeMenuLayout调整为 android:layout_width="match_parent"
    android:layout_height="match_parent"
