### ISSUE TITLE
无法为单个item设置是否可侧滑

### ISSUE THREAD

**Issue by foreverGoUp** [anzaizai/EasySwipeMenuLayout#18]
目前只有提供对整个列表是否可侧滑的接口，建议增加对单个侧滑的控制，项目需求。

**Comment by foreverGoUp** [comment]
已解决。没有直接的接口，设置单个侧滑需要把item view实例获取到，再调用EasySwipeMenuLayout实例的设置可侧滑进行实现。

**Comment by lucklygaj** [comment]
嗯嗯，感谢反馈

**Comment by lucklygaj** [comment]
后面版本会考虑进去
