### ISSUE TITLE
左滑的时候，假如没有left布局，就崩了。看了下你的源码，左滑的时候，你的判断少了个else

### ISSUE THREAD

**Issue by binzhiyuan** [anzaizai/EasySwipeMenuLayout#2]
//越界修正
                if (getScrollX() < 0) {
                    if (!mCanRightSwipe || mLeftView == null) {
                        scrollTo(0, 0);
                    }else**# //你少了这个else**
                    {//左滑
                        if (getScrollX() < mLeftView.getLeft()) {
                            scrollTo(mLeftView.getLeft(), 0);
                        }

                    }
                }

**Comment by lucklygaj** [comment]
感谢你的反馈，已修复，1.0.3版本
