### ISSUE TITLE
BaseItemDraggableAdapter的拖动功能与该库无法一起使用

### ISSUE THREAD

**Issue by foreverGoUp** [anzaizai/EasySwipeMenuLayout#22]
**情况说明**：我想要用BaseItemDraggableAdapter的拖动item进行排序功能，刚好项目需求也需要侧滑删除，于是又在布局文件中加入该库的布局代码，运行的结果是侧滑菜单正常，但是BaseItemDraggableAdapter的拖动功能失效，长按无法拖动item。我可以保证我的代码没有问题，因为独立测试2个库的功能时都正常，而合并使用就会出现问题。
**猜想**：可能是该库的EasySwipeMenuLayout事件处理拦截了长按事件，导致BaseItemDraggableAdapter的拖动无法使用。麻烦库作者大大尽快解决一下这个问题，感激！我暂时用了一个不完美的替代方案，就是用BaseItemDraggableAdapter的没有删除按钮的侧滑删除。 @githubzaibao

**Comment by lucklygaj** [comment]
你好，这个问题之前也有小伙伴反馈过，但是因为原理上的冲突，我需要获取焦点来判断是否要滑动，目前我也还没有好的解决方案，感谢你的反馈
