### ISSUE TITLE
配合BaseRecyclerViewAdapterHelper使用时，添加侧滑菜单后，设置的item点击事件失效，如果设置headview会直接崩溃

### ISSUE THREAD

**Issue by zackcaz** [anzaizai/EasySwipeMenuLayout#3]
配合BaseRecyclerViewAdapterHelper使用时，添加侧滑菜单后，设置的item点击事件失效，如果设置headview会直接崩溃，是需要做特殊处理吗？

**Comment by lucklygaj** [comment]
你好，可以贴一下代码么？

**Comment by lucklygaj** [comment]
你好，该问题与修复，item的点击事件的添加，id直接指定内容View的id 即可
