### ISSUE TITLE
如何结合BaseRecyclerViewAdapterHelper实现删除按钮点击的效果？

### ISSUE THREAD

**Issue by dotfeng** [anzaizai/EasySwipeMenuLayout#4]
adapter.setOnItemChildClickListener不起作用，单独给content添加点击事件，与侧滑冲突
``` helper.getView(R.id.content).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ((SecondActivity)mContext).openThird();
            }
        });

**Comment by lucklygaj** [comment]
直接这样子设置即可：            helper.getView(R.id.right_menu_2).setOnClickListener(new View.OnClickListener() {

感谢你的反馈

**Comment by dotfeng** [comment]
@githubzaibao 是的，这样可以给菜单添加点击，但是如果是给content添加点击的话，会与侧滑冲突，侧滑的时候就执行了content的点击，helper.getView(R.id.content).setOnClickListener(new View.OnClickListener() {

**Comment by lucklygaj** [comment]
嗯嗯，我也发现了，感谢你的反馈，解决了会给你信息。或者你有什么好的解决方法也可以分享下哦。

**Comment by lucklygaj** [comment]
你好，在最新版本1.0.4中已经修复了该问题，感谢你的反馈

**Comment by dotfeng** [comment]
@githubzaibao jitpack上的1.0.4版本状态错误，https://jitpack.io/#anzaizai/EasySwipeMenuLayout

**Comment by lucklygaj** [comment]
嗯嗯，刚上去看发现，是jitpack好像出问题了，好多人都在jitpack上提这个Issues，有最新消息会及时通知您，如果你现在急着用的话，可以通过修改源代码

**Comment by lucklygaj** [comment]
@Override
    public boolean onInterceptTouchEvent(MotionEvent event) {
        // Log.d(TAG, "dispatchTouchEvent() called with: " + "ev = [" + event + "]");

        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN: {
                break;
            }
            case MotionEvent.ACTION_MOVE: {
                //滑动时拦截点击时间
                float distance = mFirstP.x - event.getRawX();
                if (Math.abs(distance) > mScaledTouchSlop) {
                    // 当手指拖动值大于mScaledTouchSlop值时，认为应该进行滚动，拦截子控件的事件
                    //Log.i(TAG, ">>>>onInterceptTouchEvent true");
                    return true;
                }
                break;

            }主要是这一句    float distance = mFirstP.x - event.getRawX();,之前写成mLastP了

**Comment by lucklygaj** [comment]
现在可以了哦，最新的是1.0.6感谢你的反馈
