### ISSUE TITLE
调用删除无效

### ISSUE THREAD

**Issue by alguojian** [anzaizai/EasySwipeMenuLayout#5]
点击删除后，侧滑恢复原样，但是调用adapter的，adapter的方法   adapter.notifyItemRemoved(position);适配器不会发生改变，不知道是为什么

**Comment by lucklygaj** [comment]
你好可以贴一下代码呢？执行adapter.notifyItemRemoved(position);后也要把数据源的数据移除才可以的，感谢你的反馈
