### ISSUE TITLE
内容区域如果添加图片就会出现“分享或者删除”不能铺满的情况

### ISSUE THREAD

**Issue by ListenerGao** [anzaizai/EasySwipeMenuLayout#6]
<LinearLayout
                          android:id="@+id/content"
                          android:layout_width="match_parent"
                          android:layout_height="wrap_content"
                          android:background="#cccccc"
                          android:orientation="vertical"
                          android:padding="20dp">
                               
                              <TextView
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:text="内容区域" />
</LinearLayout>

**Comment by ListenerGao** [comment]
<LinearLayout
                          android:id="@+id/content"
                          android:layout_width="match_parent"
                          android:layout_height="wrap_content"
                          android:background="#cccccc"
                          android:orientation="vertical"
                          android:padding="20dp">
                              <TextView
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:text="内容区域" />
                      </LinearLayout>

**Comment by lucklygaj** [comment]
可以贴下布局代码么

**Comment by ListenerGao** [comment]
你直接在你的simple的Item中添加一个ImageView，就会复现这样情况的。如果不能你在联系我，我找找之前写的代码。

**Comment by lucklygaj** [comment]
目前的设计，你需要控制他们的高度一致，如果使用包裹父布局，三个的高度是各自维护的，我在考虑是否要以里面最高度最大值作为标准
