### ISSUE TITLE
androidX 使用fragment里套用这个，不报错，直接闪退

### ISSUE THREAD

**Issue by wqbs369** [anzaizai/EasySwipeMenuLayout#60]
`<?xml version="1.0" encoding="utf-8"?>
<androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/iv_back"
        android:layout_width="wrap_content"
        android:layout_height="45dp"
        android:layout_marginLeft="16dp"
        android:src="@drawable/ic_arrow_back_black" />

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recycle_view"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />
</androidx.appcompat.widget.LinearLayoutCompat>`
`package cn.ttxs.wq.adapter;

import com.chad.library.adapter.base.BaseQuickAdapter;
import com.chad.library.adapter.base.viewholder.BaseViewHolder;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.List;

import cn.ttxs.wq.R;

public class MsgAdapter extends BaseQuickAdapter<String, BaseViewHolder> {

    public MsgAdapter(int layoutResId, @Nullable List<String> data) {
        super(layoutResId, data);
    }

    /**
     * 在此方法中设置item数据
     */
    @Override
    protected void convert(@NotNull BaseViewHolder helper, @NotNull String item) {
        helper.setText(R.id.content, item + "This is an Item, pos: " + (helper.getAdapterPosition() - getHeaderLayoutCount()));
    }
}`
`package cn.ttxs.wq.fragment;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.chad.library.adapter.base.BaseQuickAdapter;
import com.chad.library.adapter.base.listener.OnItemChildClickListener;

import java.util.ArrayList;
import java.util.List;

import cn.ttxs.lib.base.BaseFragment;
import cn.ttxs.lib.tool.ToolLog;
import cn.ttxs.wq.R;
import cn.ttxs.wq.adapter.MsgAdapter;

public class MsgFragment extends BaseFragment {
    public static final String ARGS_PAGE = "args_page";
    private int mPage;
    private ImageView iv_back;
    private RecyclerView recyclerView;
    private List<String> dataList = new ArrayList<>();
    private MsgAdapter mAdapter;

    public static MsgFragment newInstance(int page) {
        ToolLog.w("page", "position:" + page);
        Bundle args = new Bundle();
        args.putInt(ARGS_PAGE, page);
        MsgFragment fragment = new MsgFragment();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mPage = getArguments().getInt(ARGS_PAGE);
    }

    @Override
    public int bindLayout() {
        return R.layout.fragment_msg;
    }

    @Override
    public void initView(View view, Bundle bundle) {
        super.initView(view, bundle);
        iv_back = view.findViewById(R.id.iv_back);
        recyclerView = view.findViewById(R.id.recycle_view);
        initData();
        setView();
    }

    private void initData() {
        for (int i = 0; i < 20; i++) {
            dataList.add("item" + i);
        }
        mAdapter = new MsgAdapter(R.layout.easy_swipmenu,dataList);
    }

    private void setView() {
        LinearLayoutManager layoutManager = new LinearLayoutManager(getContext());
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(layoutManager);
//        mAdapter.addChildClickViewIds(R.id.left, R.id.content, R.id.right);
//        mAdapter.setOnItemChildClickListener(new OnItemChildClickListener() {
//            @Override
//            public void onItemChildClick(@NonNull BaseQuickAdapter adapter, @NonNull View view, int position) {
//
//                switch (view.getId()) {
//                    case R.id.left:
//                        showToast("点击了：左边按钮" + position);
//                        break;
//                    case R.id.content:
//                        showToast("点击了内容" + position);
//                        break;
//                    case R.id.right:
//                        showToast("点击了右边按钮" + position);
//                        break;
//                }
//            }
//        });
//        recyclerView.setAdapter(mAdapter);
    }

    @Override
    public void doBusiness(Context mContext) {
    }
}`
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/ll_root"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginBottom="1dp"
    android:clickable="true"
    android:orientation="vertical">

    <com.guanaj.easyswipemenulibrary.EasySwipeMenuLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:contentView="@+id/content"
        app:leftMenuView="@+id/left"
        app:rightMenuView="@+id/right">

        <LinearLayout
            android:id="@+id/left"
            android:layout_width="100dp"
            android:layout_height="wrap_content"
            android:background="@android:color/holo_blue_dark"
            android:orientation="horizontal"
            android:padding="20dp">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="分享" />
        </LinearLayout>

        <LinearLayout
            android:id="@+id/content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#cccccc"
            android:orientation="vertical"
            android:padding="20dp">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="内容区域" />
        </LinearLayout>

        <LinearLayout
            android:id="@+id/right"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@android:color/holo_red_light"
            android:orientation="horizontal">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@android:color/holo_blue_bright"
                android:padding="20dp"
                android:text="删除" />

            <TextView
                android:id="@+id/right_menu_2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@android:color/holo_orange_dark"
                android:padding="20dp"
                android:text="收藏" />
        </LinearLayout>
    </com.guanaj.easyswipemenulibrary.EasySwipeMenuLayout>
</LinearLayout>`

上面是itemlayout,有没有大神使用androidX的viewpager+fragment,我的viewpager使用的是不NoScrollViewPager

**Comment by lucklygaj** [comment]
闪退的错误堆栈信息可以提供以下

**Comment by wqbs369** [comment]
关键就是没有堆栈错误信息啊,下午终于看到log了,已经OK了.android studio抽疯了
