### ISSUE TITLE
在viewpager中会有滑动冲突

### ISSUE THREAD

**Issue by cizkey** [anzaizai/EasySwipeMenuLayout#7]
您好, 这个库写很棒,思路很好, 但是在viewpager中会有滑动冲突.

viewpager中有recyclerview,  item项使用该布局.
会出现只能滑动ViewPager而不能滑动item的现象.

**Comment by lucklygaj** [comment]
这个，你需要有个处理滑动冲突的需求，比如在某个点是应该触发viewpager的，哪个点是触发item的
