### ISSUE TITLE
滑动不灵敏

### ISSUE THREAD

**Issue by ArthurWangYB** [anzaizai/EasySwipeMenuLayout#8]
与BaseRecyclerViewAdapterHelper一同使用，没有嵌套像viewpager之类的滚动试图，滑动非常不灵敏，有时能出来，有时一直划不出

**Comment by ArthurWangYB** [comment]
收回的时候还好，滑出的时候根本不能一点点滑出，只能飞速滑动一大截距离，然后一下就出来了

**Comment by ArthurWangYB** [comment]
建议作者可以结合BaseRecyclerViewAdapterHelper写一个demo，用真机运行可以了解具体的情况，还可以给使用者作为参考0.0

**Comment by lucklygaj** [comment]
感谢你的反馈，有最新的会及时通知你的

**Comment by lucklygaj** [comment]
你好，最新的1.0.7优化了该问题，感谢您的反馈！
