### ISSUE TITLE
无聊的人三指操作

### ISSUE THREAD

**Issue by ArthurWangYB** [anzaizai/EasySwipeMenuLayout#9]
三指分别划三个item。。。都划出来了。。。

**Comment by cizkey** [comment]
这个可以禁用布局的多点触控解决

**Comment by lucklygaj** [comment]
目前还没想到在EasySwipeMenuLayout中能控制的方案，测试了一些，三指以后控制成功率就降低了，大家有好的方案可以提一下哦，感谢大家的反馈

**Comment by Lalalatte** [comment]
@cizkey 的方法可以，粘个代码吧
`android:splitMotionEvents="false"`
